### PR TITLE
declare variables and remove unused

### PR DESCRIPTION
**Pull request by igncp**
Hi there,

A few variables were not declared, so they were attached to the global scope (i.e. `window`). You can try it with any of them in the project website, for example you can see from a browser's console `window.headIndex` or `window.$table` have a value. Also removed some variables that were not used, to spare a few bits. Hope it helps.

Cheers

### CODE REVIEW

**Comment by torounit** [comment]
+1

**Comment by johnpolacek** [comment]
Thanks!

**Comment by Grawl** [comment]
please update NPM published package with this update. I just got broken old version from NPM without those fixes.

**Comment by johnpolacek** [comment]
@Grawl Updated to 1.0.3 now.

**Pull request merged**
